### ISSUE TITLE
Installation issue - Permission denied (publickey,keyboard-interactive). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by vikaskalra** [aligent/PINpayments#5]
Whenever I try to install using "modman clone git@git.assembla.com:aligent.pinpay.git"

I get the following ERROR output, do I need special rights?

Cloning into 'aligent.pinpay'...
Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: trying to clone new module 'aligent.pinpay', operation cancelled.

**Comment by andrew-dwyer** [comment]
@vikaskalra Try the following instead. I'll update the readme
`modman clone git@github.com:aligent/PINpayments.git`

**Comment by vikaskalra** [comment]
Same issue - I am using CentOS.


modman clone git@github.com:aligent/PINpayments.git
Cloning into 'PINpayments'...
The authenticity of host 'github.com (192.30.252.128)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: trying to clone new module 'PINpayments', operation cancelled.

**Comment by andrew-dwyer** [comment]
@vikaskalra You may not have SSH keys configured. Either switch to using the HTTPS remote or configure your public key on github. See this guide https://help.github.com/articles/set-up-git/
